//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_aSINTO_GRUPOPREGUNTA> tbl_aSINTO_GRUPOPREGUNTA { get; set; }
        public virtual DbSet<tbl_aSINTO_MENSAJES> tbl_aSINTO_MENSAJES { get; set; }
        public virtual DbSet<tbl_aSINTO_OPCIONES> tbl_aSINTO_OPCIONES { get; set; }
        public virtual DbSet<tbl_aSINTO_PREGUNTA> tbl_aSINTO_PREGUNTA { get; set; }
        public virtual DbSet<tbl_aSINTO_PROCESO> tbl_aSINTO_PROCESO { get; set; }
        public virtual DbSet<tbl_aSINTO_REGISTRO> tbl_aSINTO_REGISTRO { get; set; }
        public virtual DbSet<tbl_aSINTO_REPORTE> tbl_aSINTO_REPORTE { get; set; }
        public virtual DbSet<tbl_aSINTO_RESPUESTA> tbl_aSINTO_RESPUESTA { get; set; }
        public virtual DbSet<tbl_aSINTO_TIPOPREGUNTA> tbl_aSINTO_TIPOPREGUNTA { get; set; }
        public virtual DbSet<tbl_mSINTO_COLABORADOR> tbl_mSINTO_COLABORADOR { get; set; }
        public virtual DbSet<tbl_mSINTO_FORMULARIO> tbl_mSINTO_FORMULARIO { get; set; }
    
        public virtual int SP_PROCESAR_SINTOMATOLOGIA(Nullable<int> cODIGO)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PROCESAR_SINTOMATOLOGIA", cODIGOParameter);
        }
    
        public virtual int USP_REPORTESINTO(Nullable<int> cODIGOREGISTRO)
        {
            var cODIGOREGISTROParameter = cODIGOREGISTRO.HasValue ?
                new ObjectParameter("CODIGOREGISTRO", cODIGOREGISTRO) :
                new ObjectParameter("CODIGOREGISTRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_REPORTESINTO", cODIGOREGISTROParameter);
        }
    }
}
