//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSINTO_OPCIONES
    {
        public int CODIGOOPCION { get; set; }
        public string OPCION { get; set; }
        public int ESTADO { get; set; }
        public Nullable<int> CODIGOPREGUNTA { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<int> FLAGOTRO { get; set; }
        public Nullable<int> CODIGOPREGUNTA_MOSTRAR { get; set; }
    
        public virtual tbl_aSINTO_PREGUNTA tbl_aSINTO_PREGUNTA { get; set; }
    }
}
