//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSINTO_REGISTRO
    {
        public int CODREGISTRO { get; set; }
        public int CODAUTOGENERADO { get; set; }
        public int CODIGOFORMULARIO { get; set; }
        public string PUESTO { get; set; }
        public string AREA { get; set; }
        public string CELULAR { get; set; }
        public Nullable<int> ANEXO { get; set; }
        public Nullable<bool> CHECKTERMINOS { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public Nullable<bool> ESCOLABORADOR { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> PROCESADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CODIGOMENSAJE { get; set; }
    
        public virtual tbl_aSINTO_MENSAJES tbl_aSINTO_MENSAJES { get; set; }
    }
}
