//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSINTO_REPORTE
    {
        public int ID { get; set; }
        public string DNINOMBRE { get; set; }
        public string CELULAR { get; set; }
        public System.DateTime FECHAREGISTRO { get; set; }
        public string OFICINASEDE { get; set; }
        public string TIPOTRABAJADOR { get; set; }
        public string SINTOFAMILIAR { get; set; }
        public string VACUNADO { get; set; }
        public string FORMATRABAJO { get; set; }
    }
}
