//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mSINTO_FORMULARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mSINTO_FORMULARIO()
        {
            this.tbl_aSINTO_GRUPOPREGUNTA = new HashSet<tbl_aSINTO_GRUPOPREGUNTA>();
        }
    
        public int CODIGOFORMULARIO { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCIONTITULO { get; set; }
        public string SUBTITULO { get; set; }
        public string DESCRIPCIONSUBTITULO { get; set; }
        public string TERMINOSCONDICIONES { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aSINTO_GRUPOPREGUNTA> tbl_aSINTO_GRUPOPREGUNTA { get; set; }
    }
}
