//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSINTO_RESPUESTA
    {
        public int CODGIORESPUESTA { get; set; }
        public int CODREGISTRO { get; set; }
        public int CODIGOGRUPO { get; set; }
        public int CODIGOPREGUNTA { get; set; }
        public string TEXTO_OTRO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string OPCION { get; set; }
        public string OPCION2 { get; set; }
    }
}
