//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSINTO_PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_aSINTO_PREGUNTA()
        {
            this.tbl_aSINTO_OPCIONES = new HashSet<tbl_aSINTO_OPCIONES>();
        }
    
        public int CODIGOPREGUNTA { get; set; }
        public string PREGUNTA { get; set; }
        public Nullable<int> CODIGOGRUPO { get; set; }
        public int ESTADO { get; set; }
        public Nullable<int> CODIGOTIPOPREGUNTA { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<int> OBLIGATORIO { get; set; }
        public Nullable<bool> DEPENDIENTE { get; set; }
        public string TEXTO_AYUDA { get; set; }
    
        public virtual tbl_aSINTO_GRUPOPREGUNTA tbl_aSINTO_GRUPOPREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aSINTO_OPCIONES> tbl_aSINTO_OPCIONES { get; set; }
        public virtual tbl_aSINTO_TIPOPREGUNTA tbl_aSINTO_TIPOPREGUNTA { get; set; }
    }
}
