//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mSINTO_COLABORADOR
    {
        public int CODAUTOGENERADO { get; set; }
        public int CODCOLABORADOR { get; set; }
        public string NOMBRESAPELLIDOS { get; set; }
        public string DOCUMENTO { get; set; }
        public string PUESTO { get; set; }
        public string AREA { get; set; }
        public string CELULAR { get; set; }
        public string CORREO { get; set; }
        public string USUARIOWINDOWS { get; set; }
        public Nullable<bool> ESCOLABORADOR { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> ANEXO { get; set; }
    }
}
