//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aSINTO_MENSAJES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_aSINTO_MENSAJES()
        {
            this.tbl_aSINTO_REGISTRO = new HashSet<tbl_aSINTO_REGISTRO>();
        }
    
        public int CODIGOMENSAJE { get; set; }
        public string MENSAJE { get; set; }
        public string MENSAJEHTML { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_aSINTO_REGISTRO> tbl_aSINTO_REGISTRO { get; set; }
    }
}
